language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install codecov -g
  - curl -sL firebase.tools | bash
branches:
  except:
    - gh-pages
stages:
  - lint
  - unit test
  - e2e test
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - npm run lint
    - stage: unit test
      before_script:
        - chmod +x ./firebaseEmulator.sh
      script:
        # Run tests
        - sh ./firebaseEmulator.sh
      after_success:
        - codecov -f ./coverage/coverage-final.json
    - stage: e2e test
      script:
        # Run e2e test
        - npm run test:e2e
