language: node_js
node_js:
  - "node"
install:
  - npm install
  - curl -sL firebase.tools | bash
branches:
  except:
    - gh-pages
stages:
  - lint
  - unit test
  - e2e test
  - coverage
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - npm run lint
    - stage: unit test
      script:
        # Run tests
        - firebase emulator:start
        - npm run test:unit
    - stage: e2e test
      script:
        # Run e2e test
        - npm run test:e2e
    - stage: coverage
      script:
        codecov
